---
- hosts: mywebservers
  become: yes
  tasks:
  - name: i want to install my webserver on ansible nodes
    apt:
      name: apache2
      state: present
  
  - name: i want start my webserver on ansible nodes
    service:
      name: apache2
      state: started
